import {
    array_contains,
} from "std/array"
import {
    dir_create,
    dir_exists,
    file_chmod,
    file_exists,
    file_write,
    symlink_create,
} from "std/fs"
import {
    split,
    replace,
    rpad,
} from "std/text"

const user_home = trust $ sudo -u#1000 bash -c 'echo \$HOME' $

#[allow_absurd_cast]
pub fun dconf_list() {
    const keys = split($ jq -r '.dconf | keys | .[]' ~/.config/declair/config.json $?, "\n")
    const longest_key_col = $ jq -r '.dconf | keys | .[]' ~/.config/declair/config.json | wc -L $? as Int
    const longest_val_col = $ jq -r '.dconf | values | .[]' ~/.config/declair/config.json | wc -L $? as Int
    let longest_actual_val_col = 0
    for key in keys {
        const desired = $ jq -r '.dconf["{key}"]' ~/.config/declair/config.json $?
        let state = "Unknown"
        let actual = "-"
        actual = trust $ dconf read '{key}' $
        if len(actual) > longest_actual_val_col {
            longest_actual_val_col = len(actual)
        }
        if actual == desired {
            state = "OK"
        } else {
            state = "Mismatched"
        }
        // TODO: Colorize
        echo rpad(key, " ", longest_key_col + 2) + rpad(desired, " ", longest_val_col+2) + rpad(actual, " ", longest_actual_val_col + 2) + state
    }
}

// pub fun dconf_ensure(pkg: Text): Null?  {
//     $ sudo dnf install -y {pkg} $ failed {
//         return null
//     }
//     const installed = get_installed_version(pkg)?
//     const updated_json = $ jq '.rpm["{pkg}"] = "{installed}"' ~/.config/declair/config.json $ failed {
//         echo "Failed to update declair config file."
//         return null
//     }
//     file_write("{user_home}/.config/declair/config.json", updated_json) failed {
//         echo "Failed to update declair config file."
//         return null
//     }
// }

pub fun dconf_write(key: Text, value: Text): Null  {
    $ dconf write '{key}' '{value}' $ failed {
        echo "write failed"
        return null
    }
    const updated_json = $ jq '.dconf["{key}"] = "{value}"' ~/.config/declair/config.json $ failed {
        echo "Failed to update declair config file."
        return null
    }
    file_write("{user_home}/.config/declair/config.json", updated_json) failed {
        echo "Failed to update declair config file."
        return null
    }
    echo "Done"
}
