import * from "./gitconfig.ab"
import * from "./dconf.ab"
import * from "./pm.ab"
import * from "./sym.ab"
import * from "./rpm-repo.ab"

main(args) {
    if {
        args[1] == "gitconfig" {
            if {
                args[2] == "plan" {
                    gitconfig_plan()?
                }
                args[2] == "apply" {
                    gitconfig_apply()?
                }
                else {
                    echo "Unknown subcommand: {args[2]}"
                    echo "Available subcommands: plan apply"
                    exit 1
                }
            }
        }
        args[1] == "dconf" {
            if {
                args[2] == "list" {
                    dconf_list()?
                }

                args[2] == "write" {
                    if len(args) > 4 {
                        dconf_write(args[3], args[4])
                    } else {
                        echo "Not key and value are given"
                        exit 1
                    }
                }
                args[2] == "ensure" {
                    if len(args) > 3 {
                        dconf_ensure(args[3])?
                    } else {
                        echo "No key is given"
                        exit 1
                    }
                }
                else {
                    echo "Unknown subcommand: {args[2]}"
                    echo "Available subcommands: list write ensure"
                    exit 1
                }
            }
        }
        args[1] == "sym" {
            if {
                args[2] == "list" {
                    sym_list()?
                }

                args[2] == "ensure" {
                    if len(args) > 3 {
                        sym_ensure([args[3]])?
                    } else {
                        sym_ensure()?
                    }
                }
                else {
                    echo "Unknown subcommand: {args[2]}"
                    echo "Available subcommands: list ensure"
                    exit 1
                }
            }
        }
        args[1] == "pm" {
            if {
                args[2] == "list" {
                    pm_list()?
                }
                args[2] == "ensure" {
                    if len(args) > 3 {
                        pm_ensure(args[3])?
                    } else {
                        echo "No package given"
                        exit 1
                    }
                }
                args[2] == "install" {
                    if len(args) > 3 {
                        pm_ensure(args[3])?
                    } else {
                        echo "No package given"
                        exit 1
                    }
                }
                else {
                    echo "Unknown subcommand: {args[2]}"
                    echo "Available subcommands: list ensure install"
                    exit 1
                }
            }

        }
        args[1] == "rpm-repo" {
            if {
                args[2] == "list" {
                    dnf_repo_list()?
                }
                args[2] == "ensure" {
                    if len(args) > 3 {
                        dnf_repo_ensure(args[3])?
                    } else {
                        echo "No package given"
                        exit 1
                    }
                }
                args[2] == "install" {
                    if len(args) > 3 {
                        dnf_repo_ensure(args[3])?
                    } else {
                        echo "No package given"
                        exit 1
                    }
                }
                else {
                    echo "Unknown subcommand: {args[2]}"
                    echo "Available subcommands: list ensure install"
                    exit 1
                }
            }
        }
        else {
            echo "Unknown subcommand: {args[1]}"
            echo "Available subcommands: gitconfig sym pm rpm-repo dconf"
            exit 1
        }
    }
}
